# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _libsmoldyn
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


ECok = _libsmoldyn.ECok
ECnotify = _libsmoldyn.ECnotify
ECwarning = _libsmoldyn.ECwarning
ECnonexist = _libsmoldyn.ECnonexist
ECall = _libsmoldyn.ECall
ECmissing = _libsmoldyn.ECmissing
ECbounds = _libsmoldyn.ECbounds
ECsyntax = _libsmoldyn.ECsyntax
ECerror = _libsmoldyn.ECerror
ECmemory = _libsmoldyn.ECmemory
ECbug = _libsmoldyn.ECbug
ECsame = _libsmoldyn.ECsame
ECwildcard = _libsmoldyn.ECwildcard
smolGetVersion = _libsmoldyn.smolGetVersion
smolSetLogging = _libsmoldyn.smolSetLogging
smolSetThrowing = _libsmoldyn.smolSetThrowing
smolSetError = _libsmoldyn.smolSetError
smolSetErrorNT = _libsmoldyn.smolSetErrorNT
smolGetError = _libsmoldyn.smolGetError
smolClearError = _libsmoldyn.smolClearError
smolSetDebugMode = _libsmoldyn.smolSetDebugMode
smolErrorCodeToString = _libsmoldyn.smolErrorCodeToString
smolNewSim = _libsmoldyn.smolNewSim
smolUpdateSim = _libsmoldyn.smolUpdateSim
smolRunTimeStep = _libsmoldyn.smolRunTimeStep
smolRunSim = _libsmoldyn.smolRunSim
smolRunSimUntil = _libsmoldyn.smolRunSimUntil
smolFreeSim = _libsmoldyn.smolFreeSim
smolDisplaySim = _libsmoldyn.smolDisplaySim
smolPrepareSimFromFile = _libsmoldyn.smolPrepareSimFromFile
smolLoadSimFromFile = _libsmoldyn.smolLoadSimFromFile
smolReadConfigString = _libsmoldyn.smolReadConfigString
smolSetSimTimes = _libsmoldyn.smolSetSimTimes
smolSetTimeStart = _libsmoldyn.smolSetTimeStart
smolSetTimeStop = _libsmoldyn.smolSetTimeStop
smolSetTimeNow = _libsmoldyn.smolSetTimeNow
smolSetTimeStep = _libsmoldyn.smolSetTimeStep
smolSetRandomSeed = _libsmoldyn.smolSetRandomSeed
smolSetPartitions = _libsmoldyn.smolSetPartitions
smolSetGraphicsParams = _libsmoldyn.smolSetGraphicsParams
smolSetTiffParams = _libsmoldyn.smolSetTiffParams
smolSetLightParams = _libsmoldyn.smolSetLightParams
smolSetBackgroundStyle = _libsmoldyn.smolSetBackgroundStyle
smolSetFrameStyle = _libsmoldyn.smolSetFrameStyle
smolSetGridStyle = _libsmoldyn.smolSetGridStyle
smolSetTextStyle = _libsmoldyn.smolSetTextStyle
smolAddTextDisplay = _libsmoldyn.smolAddTextDisplay
smolSetOutputPath = _libsmoldyn.smolSetOutputPath
smolAddOutputFile = _libsmoldyn.smolAddOutputFile
smolAddCommand = _libsmoldyn.smolAddCommand
smolAddCommandFromString = _libsmoldyn.smolAddCommandFromString
smolAddSpecies = _libsmoldyn.smolAddSpecies
smolGetSpeciesIndex = _libsmoldyn.smolGetSpeciesIndex
smolGetSpeciesIndexNT = _libsmoldyn.smolGetSpeciesIndexNT
smolGetSpeciesName = _libsmoldyn.smolGetSpeciesName
smolSetSpeciesMobility = _libsmoldyn.smolSetSpeciesMobility
smolAddMolList = _libsmoldyn.smolAddMolList
smolGetMolListIndex = _libsmoldyn.smolGetMolListIndex
smolGetMolListIndexNT = _libsmoldyn.smolGetMolListIndexNT
smolGetMolListName = _libsmoldyn.smolGetMolListName
smolSetMolList = _libsmoldyn.smolSetMolList
smolSetMaxMolecules = _libsmoldyn.smolSetMaxMolecules
smolAddSolutionMolecules = _libsmoldyn.smolAddSolutionMolecules
smolAddCompartmentMolecules = _libsmoldyn.smolAddCompartmentMolecules
smolAddSurfaceMolecules = _libsmoldyn.smolAddSurfaceMolecules
smolGetMoleculeCount = _libsmoldyn.smolGetMoleculeCount
smolSetMoleculeStyle = _libsmoldyn.smolSetMoleculeStyle
smolSetBoundaryType = _libsmoldyn.smolSetBoundaryType
smolAddSurface = _libsmoldyn.smolAddSurface
smolGetSurfaceIndex = _libsmoldyn.smolGetSurfaceIndex
smolGetSurfaceIndexNT = _libsmoldyn.smolGetSurfaceIndexNT
smolGetSurfaceName = _libsmoldyn.smolGetSurfaceName
smolSetSurfaceAction = _libsmoldyn.smolSetSurfaceAction
smolSetSurfaceRate = _libsmoldyn.smolSetSurfaceRate
smolAddPanel = _libsmoldyn.smolAddPanel
smolGetPanelIndex = _libsmoldyn.smolGetPanelIndex
smolGetPanelIndexNT = _libsmoldyn.smolGetPanelIndexNT
smolGetPanelName = _libsmoldyn.smolGetPanelName
smolSetPanelJump = _libsmoldyn.smolSetPanelJump
smolAddSurfaceUnboundedEmitter = _libsmoldyn.smolAddSurfaceUnboundedEmitter
smolSetSurfaceSimParams = _libsmoldyn.smolSetSurfaceSimParams
smolAddPanelNeighbor = _libsmoldyn.smolAddPanelNeighbor
smolSetSurfaceStyle = _libsmoldyn.smolSetSurfaceStyle
smolAddCompartment = _libsmoldyn.smolAddCompartment
smolGetCompartmentIndex = _libsmoldyn.smolGetCompartmentIndex
smolGetCompartmentIndexNT = _libsmoldyn.smolGetCompartmentIndexNT
smolGetCompartmentName = _libsmoldyn.smolGetCompartmentName
smolAddCompartmentSurface = _libsmoldyn.smolAddCompartmentSurface
smolAddCompartmentPoint = _libsmoldyn.smolAddCompartmentPoint
smolAddCompartmentLogic = _libsmoldyn.smolAddCompartmentLogic
smolAddReaction = _libsmoldyn.smolAddReaction
smolGetReactionIndex = _libsmoldyn.smolGetReactionIndex
smolGetReactionIndexNT = _libsmoldyn.smolGetReactionIndexNT
smolGetReactionName = _libsmoldyn.smolGetReactionName
smolSetReactionRate = _libsmoldyn.smolSetReactionRate
smolSetReactionRegion = _libsmoldyn.smolSetReactionRegion
smolSetReactionProducts = _libsmoldyn.smolSetReactionProducts
smolAddPort = _libsmoldyn.smolAddPort
smolGetPortIndex = _libsmoldyn.smolGetPortIndex
smolGetPortIndexNT = _libsmoldyn.smolGetPortIndexNT
smolGetPortName = _libsmoldyn.smolGetPortName
smolAddPortMolecules = _libsmoldyn.smolAddPortMolecules
smolGetPortMolecules = _libsmoldyn.smolGetPortMolecules


